name: Notify Slack when UT doesn't pass
on:
  pull_request:
    branches:
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
      - production
      - mt-main
      - Trial_Prod
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run unit test
        id: unit-test
        continue-on-error: true
        run: |
          cd src
          python -m unittest test_equation.TestFirst
      - name: Build docker image
        id: docker-build
        continue-on-error: true
        run: |
          cd src
          docker build -t equation .

      - name: Notify Slack - Failure
        id: slack-failure
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ steps.docker-build.outcome == 'failure' || steps.unit-test.outcome == 'failure'}}
        with:
          channel-id: 'C03LYDHJ4J2' 
          slack-message: "*The following PR to `${{ github.event.pull_request.base.ref }}` branch failed Build :pepe_alert:*\n*Repository:* pricing_service\n*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Contributor :* <@${{ steps.map-github-slack.outputs.SLACK_ID }}>\n\n:logo_github_icon_143196: Hi <@U045UV124A0>, <@U01U6B8P3FU>, <@U06CKNZC9FH>, <@U034CLEKGDN>, <@U05G9K7TUQP>, <!subteam^S06GHNC61B6>. Please take a look."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify Slack - Success (Reply)
        id: slack-success
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ steps.docker-build.outcome == 'success' && steps.unit-test.outcome == 'success' }}
        with:
          thread_ts: ${{ steps.slack-failure.outputs.ts }} # Reply to the failure message
          channel-id: 'C03LYDHJ4J2' 
          slack-message: "*Build Succeeded! :white_check_mark:*\nThe issues have been resolved for PR `${{ github.event.pull_request.title }}`. Tests are passing."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}