name: Notify Slack when UT and build image
on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'release/*'
#       - 'feature/*'
#       - 'hotfix/*'
#   pull_request:
#     types: [closed]
#     branches:
#       - 'release/*'
#       - 'feature/*'
#       - 'hotfix/*'



jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: build image
  #       run: |
  #         cd src
  #         docker build -t equation .
  
  check-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit test
        id: unit-test
        continue-on-error: true
        run: |
          cd src
          python -m unittest test_equation.TestFirst

      - name: Build Docker image
        id: docker-build
        continue-on-error: true
        run: docker build -t my-nginx-image -f Dockerfile .

      # Notify Slack about the outcome
      - name: Notify Slack
        uses: abinoda/slack-action@master
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          message: >
            {
              "text": "Workflow `${{ github.workflow }}` run by ${{ github.actor }} _${{ job.status }}_",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "fields": [
                    {
                      "title": "Unit Test",
                      "value": "${{ steps.unit-test.outcome }}",
                      "short": true
                    },
                    {
                      "title": "Docker Build",
                      "value": "${{ steps.docker-build.outcome }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}