name: Notify Slack when UT and build image
on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'release/*'
#       - 'feature/*'
#       - 'hotfix/*'
#   pull_request:
#     types: [closed]
#     branches:
#       - 'release/*'
#       - 'feature/*'
#       - 'hotfix/*'

jobs:
  check-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit test
        id: unit-test
        continue-on-error: true
        run: |
          cd src
          python -m unittest test_equation.TestFirst
          echo "unit_test_outcome=$?" >> $GITHUB_ENV

      - name: Build Docker image
        id: docker-build
        continue-on-error: true
        run: |
          docker build -t my-nginx-image -f Dockerfile .
          echo "docker_build_outcome=$?" >> $GITHUB_ENV

      - name: Notify Slack - Failure
        if: ${{ env.unit_test_outcome != '0' || env.docker_build_outcome != '0' }}
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"The following PR to `${{ github.event.pull_request.base.ref }}` branch failed *Unit Test* :pepe_alert: "}}, {"type":"section","text":{"type":"mrkdwn","text":"*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"}}, {"type":"section","text":{"type":"mrkdwn","text":"*Contributor :* <https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>\\n\\n:logo_github_icon_143196: Hi <@U045UV124A0>, <@U01U6B8P3FU>. Please take a look."}}]}'

      - name: Notify Slack - Success
        if: ${{ env.unit_test_outcome == '0' && env.docker_build_outcome == '0' }}
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"The following PR to `${{ github.event.pull_request.base.ref }}` branch success *Unit Test* :tada: "}}, {"type":"section","text":{"type":"mrkdwn","text":"*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"}}, {"type":"section","text":{"type":"mrkdwn","text":"*Contributor :* <https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>\\n\\n:logo_github_icon_143196: Hi <@U045UV124A0>, <@U01U6B8P3FU>. Please take a look."}}]}'