name: Notify Slack when UT and build image
on:
  pull_request:
    branches:
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
      - production
      - mt-main
      - Trial_Prod
      - master
      - main

jobs:
  check-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit test
        id: unit-test
        continue-on-error: true
        run: |
          cd src
          python -m unittest test_equation.TestFirst
          echo "unit_test_outcome=$?" >> $GITHUB_ENV

      - name: Build Docker image
        id: docker-build
        continue-on-error: true
        run: |
          docker build -t my-nginx-image -f Dockerfile .
          echo "docker_build_outcome=$?" >> $GITHUB_ENV
      - name: Map GitHub to Slack ID
        id: map-github-slack
        run: |
          SLACK_ID=$(jq -r '.["${{ github.event.pull_request.user.login }}"]' .github/github_to_slack_mapping.json)
          echo "SLACK_ID=$SLACK_ID" >> $GITHUB_ENV
      - name: Notify Slack - Failure
        if: ${{ steps.docker-build.outcome == 'failure' || steps.unit-test.outcome == 'failure' }}
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"The following PR to `${{ github.event.pull_request.base.ref }}` branch failed Build :pepe_alert: \"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* <https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>\n\n:logo_github_icon_143196: Hi <@U045UV124A0>, <@U01U6B8P3FU>. Please take a look.\"}}]}'

      - name: Notify Slack - Success
        if: ${{ steps.docker-build.outcome == 'success' && steps.unit-test.outcome == 'success' }}
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"The following PR to `${{ github.event.pull_request.base.ref }}` branch success Build :tada: \"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* <https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>\n\n:logo_github_icon_143196: Hi <@U045UV124A0>, <@U01U6B8P3FU>. Please take a look <@$SLACK_ID>.\"}}]}'