name: Notify Slack when UT and build image
on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'release/*'
#       - 'feature/*'
#       - 'hotfix/*'
#   pull_request:
#     types: [closed]
#     branches:
#       - 'release/*'
#       - 'feature/*'
#       - 'hotfix/*'



jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: build image
  #       run: |
  #         cd src
  #         docker build -t equation .
  
  check-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit test
        id: unit-test
        continue-on-error: true
        run: |
          cd src
          python -m unittest test_equation.TestFirst

      - name: Build Docker image
        id: docker-build
        continue-on-error: true
        run: docker build -t my-nginx-image -f Dockerfile .

      # Notify Slack about the outcome
      - name: Notify Slack
        uses: some-slack-action/slack@v1
        if: ${{ always() }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"The following PR to `${{ github.event.pull_request.base.ref }}` branch passed *Unit Test* :tada: \"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Great work <https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>!\"}}]}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
