name: My Tag Triggered Workflow 
on:
  push:
    tags:
      - 'mt-main-*' # Trigger on tags starting with 'v' (you can adjust the pattern)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build image
        run: |
          cd src
          docker build -t equation .